connectedin/connectedin/urls.py
from django.contrib import admin
from django.contrib.auth import views as v
from django.urls import path
from perfis import views as perfil_v
from timeline import views as timeline_v
from usuarios.views import RegistrarUsuarioView
from timeline.views import TimelineView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', perfil_v.index, name='index'),
    path('perfil/<int:perfil_id>', perfil_v.display, name='exibir'),
    path('perfil/<int:perfil_id>/convidar',
         perfil_v.convidar, name='convidar'),
    path('convite/<int:convite_id>/aceitar', perfil_v.aceitar, name='aceitar'),
    path('registrar/', RegistrarUsuarioView.as_view(), name='registrar'),
    path('login/', v.LoginView.as_view(template_name="login.html"), name='login'),
    path('logout/', v.LogoutView.as_view(template_name="login.html"), name='logout'),
    path('timeline/', TimelineView.as_view(), name='timeline'),
    path('postar/', timeline_v.postar, name='postar')
]

connectedin/perfis/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import F


class Perfil(models.Model):
    nome = models.CharField(max_length=255, null=False)
    #email = models.CharField(max_length=255, null=False)
    telefone = models.CharField(max_length=15, null=False)
    nome_empresa = models.CharField(max_length=255, null=False)
    contatos = models.ManyToManyField('self', related_name='contatos')
    
    usuario = models.OneToOneField(User, related_name="perfil", on_delete=models.CASCADE)
    
    @property
    def email(self):
        return self.usuario.email
    
    def convidar(self, perfil_convidado):
        Convite(solicitante=self, convidado=perfil_convidado).save()


class Convite(models.Model):
    solicitante = models.ForeignKey(
        Perfil, related_name='convites_feitos', on_delete=models.CASCADE)
    convidado = models.ForeignKey(
        Perfil, related_name='convites_recebidos', on_delete=models.CASCADE)

    def aceitar(self):
        self.convidado.contatos.add(self.solicitante)
        self.solicitante.contatos.add(self.convidado)       
        self.delete()
        
class Postagem(models.Model):
    texto = models.CharField(max_length=200)
    data = models.TimeField(blank=True, auto_now=True)
    perfil = models.ForeignKey(Perfil, on_delete=models.CASCADE)
    
    class Meta:
        ordering = [F('data').desc(nulls_last=True)]

connectedin/usuarios/models.py
from django.db import models

# Create your models here.

connectedin/usuarios/forms.py
from django import forms
from django.contrib.auth.models import User

class RegistrarUsuarioForm(forms.Form):
    nome = forms.CharField(required=True)
    email = forms.EmailField(required=True)
    senha = forms.CharField(required=True)
    telefone = forms.CharField(required=True)
    nome_empresa = forms.CharField(required=True)
    
    def is_valid(self):
        valid = True
        if not super(RegistrarUsuarioForm, self).is_valid():
            self.adiciona_erro('Veifique seus dados!')
            valid = False
        
        user_exists = User.objects.filter(username=self.cleaned_data['nome']).exists()
        if user_exists:
            self.adiciona_erro('Usuário já existe no sistema!')
            valid = False
        
        return valid
    
    def adiciona_erro(self, message):
        errors = self._erros.setdefault(forms.forms.NON_FIELD_ERRORS, forms.utils.ErrorList())
        errors.append(message)

connectedin/perfis/views.py
from perfis.models import Perfil, Convite
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from perfis.models import Perfil, Postagem


@login_required
def index(request):
    perfil_logado = get_perfil_logado(request)
    context = {}
    context['perfis'] = Perfil.objects.all()
    context['perfil_logado'] = get_perfil_logado(request)
    context['postagens'] = Postagem.objects.all().order_by("-data")
    context['contatos'] = perfil_logado.contatos.all()
    return render(request, 'index.html', context)


@login_required
def display(request, perfil_id):
    perfil = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    eh_contato = perfil in perfil_logado.contatos.all()

    return render(request, 'perfil.html',
                  {'perfil' : perfil, 
                   'perfil_logado' : get_perfil_logado(request),
                   'eh_contato' : eh_contato,
                   'postagens': Postagem.objects.all().order_by("-data")})
    

@login_required
def convidar(request, perfil_id):
    perfil_convidar = Perfil.objects.get(id=perfil_id)
    perfil_logado = get_perfil_logado(request)
    if perfil_logado != perfil_convidar:
        perfil_logado.convidar(perfil_convidar)
    return redirect(index)


@login_required
def get_perfil_logado(request):
    return request.user.perfil


@login_required
def aceitar(request, convite_id):
    convite = Convite.objects.get(id=convite_id)
    convite.aceitar()
    return redirect('index')

connectedin/timeline/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.decorators import login_required
from perfis.models import Perfil, Postagem
from perfis.views import *


class TimelineView(View):
    template_name = 'timeline.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        return render(request, self.template_name)


@login_required
def postar(request):
    perfil = get_perfil_logado(request)
    texto = request.GET['texto']
    Postagem.objects.create(perfil=perfil, texto=texto)
    return redirect('index')
    

connectedin/usuarios/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import View
from django.contrib.auth.models import User
from perfis.models import Perfil
from usuarios.forms import RegistrarUsuarioForm

class RegistrarUsuarioView(View):
    template_name = 'registrar.html'
    
    def get(self, request):
        return render(request, self.template_name)
    
    def post(self, request):
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            dados_form = form.cleaned_data
            usuario = User.objects.create_user(username = dados_form['nome'],
                                               email = dados_form['email'],
                                               password = dados_form['senha'])
            
            perfil = Perfil(nome = dados_form['nome'],
                            telefone = dados_form['telefone'],
                            nome_empresa = dados_form['nome_empresa'],
                            usuario = usuario)
            
            perfil.save()
            return redirect('login')
        
        return render(request, self.template_name, {'form' : form})
    
    

connectedin/perfis/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>ConnectedIn</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet"/>
        <link href="{% static "styles/main.css" %}" rel="stylesheet"/>        
    </head>
    <body>
        <div class="container">
            <div class="header">
                <ul class="nav nav-pills pull-right">
                    <li><a href="{% url 'index' %}">{{perfil_logado.nome}}</a></li>
                    <li><a href="/logout/">Logout</a></li>
                </ul>
                <h3 class="text-muted">Bem vindo ao ConnectedIn</h3>
            </div>
            <div class="row content">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

connectedin/perfis/templates/index.html
{% extends "base.html" %}
{% block body %}
    <div class="col-lg-10">
        <div class="panel-heading">
        <!- Exibir Perfis->
            <strong>Perfis</strong>
            {% if perfis %}
                <ul> 
                    {% for perfil in perfis%}
                        <li>
                            <a href="{% url 'exibir' perfil.id%}">
                                {{ perfil.nome }} / {{perfil.email}}
                            </a>  
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>Nenhum perfil encontrado</p>
            {% endif %}



            <!- Painel de Convites->
            <div class="panel panel-default">
                {% with convites=perfil_logado.convites_recebidos %}
                    {% if convites.count %}
                        <div class="panel-heading">
                            <strong>
                                Você tem {{ convites.count }} 
                                convite{{convites.count|pluralize}}
                                aguardando aprovação!!!
                            </strong>
                        </div>
                        <ul class="list-group">
                            {% for convite in convites.all %}
                                <li class="list-group-item"> 
                                    {{ convite.solicitante.nome }} 
                                    <a href="{% url 'aceitar' convite.id %}" 
                                        class="pull-right">Aceitar
                                    </a>
                                </li>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <div class="panel-body">
                            <strong>
                                <p>Nenhum convite recebido!!! </p>
                            </strong>
                        </div>
                    {% endif %}
                {% endwith %}
            </div>

            <!- Nova Postagem->
            <div class="panel panel-default">
              <div class="panel-heading"><strong>Nova Postagem</strong></div>
              <div class="description">
                <div class="ui form">
                  <form action="{% url 'postar' %}" method="get" id="postar">
                    <div class="field">
                      <textarea rows="2" cols="62" name="texto"></textarea>
                    </div>
                    <button type="submit" form="postar" class="ui button">Postar</button>
                  </form>
                </div>
              </div>
            </div>
            
            <!- Painel de Contatos->
            <div class="panel panel-default">
                {% with contatos=perfil_logado.contatos %}
                    {% if contatos.count %}
                        <div class="panel-heading">
                            <strong>
                                Você tem {{contatos.count}}
                                contato{{contatos.count|pluralize}}!!!
                            </strong>
                        </div>
                        <ul class="list-group">
                            {% for contato in contatos.all %}
                                <a href="{% url 'exibir' contato.id %}"class="list-group-item"> 
                                    {{ contato.nome }} // {{ contato.email }}
                                </a>
                            {% endfor %}
                        </ul>
                    {% else %}
                        <div class="panel-body">
                            <strong>
                                <p>Você não possui contatos no momento!!!</p>
                            </strong>
                        </div>
                    {% endif %}
                {% endwith %}
            </div>

            <!- Painel de Postagens->
            <div class="panel heading">
                <h3><strong>Postagens</strong></h3>
                <div class="panel panel-group">
                    {% if postagens %} 
                        {% for post in postagens %}
                        {% if post.perfil != perfil_logado and post.perfil in contatos %}
                                <div class="container">
                                        <div class="well well-default">
                                            <h4><div class="content">{{post.texto}}</div></h4>
                                            <p>Publicado por: 
                                                <a href="{% url 'exibir' post.perfil.id %}">{{post.perfil.nome}}</a>
                                            </p>
                                        </div>
                                        
                                </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </div>   
{% endblock %}

connectedin/perfis/templates/perfil.html
{% extends "base.html" %}
{% block body %}
    <div class="row">
        <div class="col-lg-10">
            <h2 style="margin-top: 0">{{perfil.nome}}</h2>
            <address>
                <p title="Empresa">Empresa: <strong>{{perfil.nome_empresa}}</strong></p>
                <p title="Telefone">Telefone: <strong>{{perfil.telefone}}</strong></p>
                <a href="mailto:{{perfil.email}}">{{perfil.email}}</a>               
            </address>
            {% if eh_contato %}
                <div class="well well-sm">
                    Vocês estão conectados!
                </div>
            {% else %}
                <a href="{% url 'convidar' perfil.id %}"class="btn btn-success" role="button">
                    Convidar
                </a>
            {% endif %} 

        
        <div class="panel heading">
            <h3><strong>Postagens</strong></h3>
            <div class="panel panel-group">
                
                {% if postagens %}  
                    {% for post in postagens %}
                       {% if post.perfil == perfil%}
                            <div class="container">
                                <p>Publicado por: 
                                    <a href="{% url 'exibir' post.perfil.id %}">{{post.perfil.nome}}</a>
                                </p>
                                <div class="well well-default">
                                    <div class="content"><h4>{{post.texto}}</h4></div>
                                </div>
                            </div>           
                        {% endif %}
                    {% endfor %}
        
                {% endif %}
            </div>
        </div>
        
        </div>
    </div>
{% endblock %}

connectedin/usuarios/templates/base_usuario.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width">
        <title>ConnectedIn</title>
        <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
        <link href="{% static "styles/signin.css" %}" rel="stylesheet">
    </head>
    <body>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

connectedin/usuarios/templates/login.html
{% extends "base_usuario.html" %}
{% block body %}
    <form class="form-signin" role="form" action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Login</h2>
        <input id="id_username" name="username" placeholder="Nome" 
            class="form-control" required autofocus>
        <input type="password" id="id_password" name="password" placeholder="Senha" 
            class="form-control" required>
        <button class="btn btn-lg btn-primary btn-block" 
            type="submit" value="Login">Login</button>

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" 
                    data-dismiss="alert" aria-label="true"></button>
            Verifique se o nome de usuário e senha estão corretos!
            </div>
        {% endif %}
        <a href="{% url 'registrar' %}">Registre-se</a>
    </form>
{% endblock %}

connectedin/usuarios/templates/registrar.html
{% extends "base_usuario.html" %}
{% block body %}
    <form class="form-signin" action="{% url 'registrar' %}" method="post">
        {% csrf_token %}
        <h2 class="form-signin-heading">Novo Usuario</h2>
        <input id="id_email" name="email" placeholder="Email *" 
            class="form-control" required autofocus>
        <input id="id_nome" name="nome" placeholder="Nome *" class="form-control" required>
        <input type="password" id="id_senha" name="senha" placeholder="Senha *" 
            class="form-control" required>
        <hr />
        <input id="id_telefone" name="telefone" placeholder="Telefone" 
            class="form-control" required>
        <input id="id_nome_empresa" name="nome_empresa" placeholder="Empresa" 
            class="form-control" required>
        <hr />
        <button class="btn btn-lg btn-primary btn-block" 
            type="submit" value="Login">Registrar</button>

        {% if form.errors %}
            <div class="alert alert-danger">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true"></button>
                {{form.non_field_errors}}
            </div>
        {% endif %}
        
    </form>
{% endblock %}